FROM php:8.1-apache

USER root
RUN a2enmod rewrite
RUN apt-get update && apt-get install -y zlib1g-dev libpng-dev libtidy-dev
RUN docker-php-ext-install pdo pdo_mysql gd tidy

COPY --chown=33:33 . /var/www/html/fluxcp/
