name: Bug Report
description: Create an Issue that details broken or unexpected behaviour
labels: [Bug Report]
body:
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **PHP**: 8.1
        - **MySQL**: MariaDB 10
    value: |
        - PHP: 
        - MySQL: 
    render: Markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Open page '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
