<?php
return array(
	pow(2,  0) => 'Novice',
	pow(2,  1) => 'Swordman',
	pow(2,  2) => 'Mage',
	pow(2,  3) => 'Archer',
	pow(2,  4) => 'Acolyte',
	pow(2,  5) => 'Merchant',
	pow(2,  6) => 'Thief',
	pow(2,  7) => 'Knight',
	pow(2,  8) => 'Priest',
	pow(2,  9) => 'Wizard',
	pow(2, 10) => 'Blacksmith',
	pow(2, 11) => 'Hunter',
	pow(2, 12) => 'Assassin',
	pow(2, 13) => 'Unused',
	pow(2, 14) => 'Crusader',
	pow(2, 15) => 'Monk',
	pow(2, 16) => 'Sage',
	pow(2, 17) => 'Rogue',
	pow(2, 18) => 'Alchemist',
	pow(2, 19) => 'Bard/Dancer',
	pow(2, 20) => 'Unused',
	pow(2, 21) => 'Taekwon',
	pow(2, 22) => 'Star Gladiator',
	pow(2, 23) => 'Soul Linker',
	pow(2, 24) => 'Gunslinger',
	pow(2, 25) => 'Ninja',
	pow(2, 26) => 'Gangsi',
	pow(2, 27) => 'Death Knight',
	pow(2, 28) => 'Dark Collector',
	pow(2, 29) => 'Kagerou/Oboro'
)
?>