<?php
return array(
	'mode_aggressive'			=> 'Aggressive',
	'mode_angry'				=> 'Angry',
	'mode_assist'				=> 'Assist',
	'mode_canattack'			=> 'Can Attack',
	'mode_canmove'				=> 'Can Move',
	'mode_castsensorchase'		=> 'Cast Sensor Chase',
	'mode_castsensoridle'		=> 'Cast Sensor Idle',
	'mode_changechase'			=> 'Change Chase',
	'mode_changetargetchase'	=> 'Change Target Chase',
	'mode_changetargetmelee'	=> 'Change Target Melee',
	'mode_detector'				=> 'Detector',
	'mode_fixeditemdrop'		=> 'Fixed Item Drop',
	'mode_ignoremagic'			=> 'Ignore Magic', 
	'mode_ignoremelee'			=> 'Ignore Melee',
	'mode_ignoremisc'			=> 'Ignore Misc',
	'mode_ignoreranged'			=> 'Ignore Ranged',
	'mode_knockbackimmune'		=> 'Knockback Immune',
	'mode_looter'				=> 'Looter',
	'mode_mvp'					=> 'MVP',
	'mode_norandomwalk'			=> 'Plant',
	'mode_randomtarget'			=> 'Random Target',
	'mode_skillimmune'			=> 'Skill Immune',
	'mode_statusimmune'			=> 'Status Immune',
	'mode_targetweak'			=> 'Target Weak',
	'mode_teleportblock'		=> 'Teleport Block',
)
?>
