<?php
return array(
	'A' => 'Admin',
	'B' => 'Buy Store',
	'C' => 'Consumed',
	'D' => 'Stolen/Ganked',
	'E' => 'Mailed',
	'F' => 'Bound Retrieval',
	'G' => 'Guild Storage',
	//'H' => '',
	'I' => 'Auctioned',
	//'J' => '',
	'K' => 'Bank',
	'L' => 'Looted',
	'M' => 'Monster',
	'N' => 'NPC (Script)',
	'O' => 'Produced',
	'P' => 'Player',
	'Q' => 'Quest',
	'R' => 'Storage',
	'S' => 'NPC (Shop)',
	'T' => 'Traded',
	'U' => 'MVP',
	'V' => 'Vended',
	//'W' => '',
	'X' => 'Other',
	'Y' => 'Lottery',
	'Z' => 'Merged',
	'$' => 'Cash',
);
?>
